- name: update local repo
  become: true  
  apt: 
    update_cache: yes
- name: upgrade apt packages
  become: true 
  apt: 
    upgrade: yes 

- name: install dependencies 
  become: true 
  apt: 
    name: "{{ item }}"
    state: latest 
    update_cache: yes
  with_items: 
    - nodejs 
    - npm 

- name: install pm2 
  become: true
  npm:  
    name: pm2 
    global: yes
    production: yes
    state: present

- name: Copy artifact to instance
  become: true 
  copy: 
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: Start app 
  become: true 
  shell: |
    cd /home/ubuntu
    tar xzvf artifact.tar.gz
    npm install 
    npm run build 
    pm2 stop all 
    pm2 start npm --start 